/*
 * This file is generated by jOOQ.
 */
package co.tide.com.fitnessapp.db.jooq;


import co.tide.com.fitnessapp.db.jooq.tables.Exercise;
import co.tide.com.fitnessapp.db.jooq.tables.Food;
import co.tide.com.fitnessapp.db.jooq.tables.Meal;
import co.tide.com.fitnessapp.db.jooq.tables.User;
import co.tide.com.fitnessapp.db.jooq.tables.Workout;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.16"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>exercise</code>.
     */
    public final Exercise EXERCISE = Exercise.EXERCISE;

    /**
     * The table <code>food</code>.
     */
    public final Food FOOD = Food.FOOD;

    /**
     * The table <code>meal</code>.
     */
    public final Meal MEAL = Meal.MEAL;

    /**
     * The table <code>user</code>.
     */
    public final User USER = User.USER;

    /**
     * The table <code>workout</code>.
     */
    public final Workout WORKOUT = Workout.WORKOUT;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Exercise.EXERCISE,
            Food.FOOD,
            Meal.MEAL,
            User.USER,
            Workout.WORKOUT);
    }
}
