/*
 * This file is generated by jOOQ.
 */
package co.tide.com.fitnessapp.db.jooq;


import co.tide.com.fitnessapp.db.jooq.tables.Exercise;
import co.tide.com.fitnessapp.db.jooq.tables.Food;
import co.tide.com.fitnessapp.db.jooq.tables.Goal;
import co.tide.com.fitnessapp.db.jooq.tables.Meal;
import co.tide.com.fitnessapp.db.jooq.tables.User;
import co.tide.com.fitnessapp.db.jooq.tables.Workout;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.16"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>exercise</code>.
     */
    public static final Exercise EXERCISE = Exercise.EXERCISE;

    /**
     * The table <code>food</code>.
     */
    public static final Food FOOD = Food.FOOD;

    /**
     * The table <code>goal</code>.
     */
    public static final Goal GOAL = Goal.GOAL;

    /**
     * The table <code>meal</code>.
     */
    public static final Meal MEAL = Meal.MEAL;

    /**
     * The table <code>user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>workout</code>.
     */
    public static final Workout WORKOUT = Workout.WORKOUT;
}
