/*
 * This file is generated by jOOQ.
 */
package co.tide.com.fitnessapp.db.jooq.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.16"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Exercise implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID          id;
    private UUID          workoutId;
    private String        exerciseName;
    private String        sets;
    private String        reps;
    private String        notes;
    private LocalDateTime createdOn;
    private LocalDateTime updatedOn;

    public Exercise() {}

    public Exercise(Exercise value) {
        this.id = value.id;
        this.workoutId = value.workoutId;
        this.exerciseName = value.exerciseName;
        this.sets = value.sets;
        this.reps = value.reps;
        this.notes = value.notes;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    @ConstructorProperties({ "id", "workoutId", "exerciseName", "sets", "reps", "notes", "createdOn", "updatedOn" })
    public Exercise(
        UUID          id,
        UUID          workoutId,
        String        exerciseName,
        String        sets,
        String        reps,
        String        notes,
        LocalDateTime createdOn,
        LocalDateTime updatedOn
    ) {
        this.id = id;
        this.workoutId = workoutId;
        this.exerciseName = exerciseName;
        this.sets = sets;
        this.reps = reps;
        this.notes = notes;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>exercise.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>exercise.id</code>.
     */
    public Exercise setId(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>exercise.workout_id</code>.
     */
    public UUID getWorkoutId() {
        return this.workoutId;
    }

    /**
     * Setter for <code>exercise.workout_id</code>.
     */
    public Exercise setWorkoutId(UUID workoutId) {
        this.workoutId = workoutId;
        return this;
    }

    /**
     * Getter for <code>exercise.exercise_name</code>.
     */
    public String getExerciseName() {
        return this.exerciseName;
    }

    /**
     * Setter for <code>exercise.exercise_name</code>.
     */
    public Exercise setExerciseName(String exerciseName) {
        this.exerciseName = exerciseName;
        return this;
    }

    /**
     * Getter for <code>exercise.sets</code>.
     */
    public String getSets() {
        return this.sets;
    }

    /**
     * Setter for <code>exercise.sets</code>.
     */
    public Exercise setSets(String sets) {
        this.sets = sets;
        return this;
    }

    /**
     * Getter for <code>exercise.reps</code>.
     */
    public String getReps() {
        return this.reps;
    }

    /**
     * Setter for <code>exercise.reps</code>.
     */
    public Exercise setReps(String reps) {
        this.reps = reps;
        return this;
    }

    /**
     * Getter for <code>exercise.notes</code>.
     */
    public String getNotes() {
        return this.notes;
    }

    /**
     * Setter for <code>exercise.notes</code>.
     */
    public Exercise setNotes(String notes) {
        this.notes = notes;
        return this;
    }

    /**
     * Getter for <code>exercise.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>exercise.created_on</code>.
     */
    public Exercise setCreatedOn(LocalDateTime createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    /**
     * Getter for <code>exercise.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>exercise.updated_on</code>.
     */
    public Exercise setUpdatedOn(LocalDateTime updatedOn) {
        this.updatedOn = updatedOn;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Exercise other = (Exercise) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (workoutId == null) {
            if (other.workoutId != null)
                return false;
        }
        else if (!workoutId.equals(other.workoutId))
            return false;
        if (exerciseName == null) {
            if (other.exerciseName != null)
                return false;
        }
        else if (!exerciseName.equals(other.exerciseName))
            return false;
        if (sets == null) {
            if (other.sets != null)
                return false;
        }
        else if (!sets.equals(other.sets))
            return false;
        if (reps == null) {
            if (other.reps != null)
                return false;
        }
        else if (!reps.equals(other.reps))
            return false;
        if (notes == null) {
            if (other.notes != null)
                return false;
        }
        else if (!notes.equals(other.notes))
            return false;
        if (createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!createdOn.equals(other.createdOn))
            return false;
        if (updatedOn == null) {
            if (other.updatedOn != null)
                return false;
        }
        else if (!updatedOn.equals(other.updatedOn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.workoutId == null) ? 0 : this.workoutId.hashCode());
        result = prime * result + ((this.exerciseName == null) ? 0 : this.exerciseName.hashCode());
        result = prime * result + ((this.sets == null) ? 0 : this.sets.hashCode());
        result = prime * result + ((this.reps == null) ? 0 : this.reps.hashCode());
        result = prime * result + ((this.notes == null) ? 0 : this.notes.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        result = prime * result + ((this.updatedOn == null) ? 0 : this.updatedOn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Exercise (");

        sb.append(id);
        sb.append(", ").append(workoutId);
        sb.append(", ").append(exerciseName);
        sb.append(", ").append(sets);
        sb.append(", ").append(reps);
        sb.append(", ").append(notes);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
