/*
 * This file is generated by jOOQ.
 */
package co.tide.com.fitnessapp.db.jooq.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.16"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Goal implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID          id;
    private UUID          userId;
    private Integer       currentWeight;
    private Integer       goalWeight;
    private String        progressStatus;
    private LocalDateTime createdOn;
    private LocalDateTime updatedOn;

    public Goal() {}

    public Goal(Goal value) {
        this.id = value.id;
        this.userId = value.userId;
        this.currentWeight = value.currentWeight;
        this.goalWeight = value.goalWeight;
        this.progressStatus = value.progressStatus;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    @ConstructorProperties({ "id", "userId", "currentWeight", "goalWeight", "progressStatus", "createdOn", "updatedOn" })
    public Goal(
        UUID          id,
        UUID          userId,
        Integer       currentWeight,
        Integer       goalWeight,
        String        progressStatus,
        LocalDateTime createdOn,
        LocalDateTime updatedOn
    ) {
        this.id = id;
        this.userId = userId;
        this.currentWeight = currentWeight;
        this.goalWeight = goalWeight;
        this.progressStatus = progressStatus;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>goal.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>goal.id</code>.
     */
    public Goal setId(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>goal.user_id</code>.
     */
    public UUID getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>goal.user_id</code>.
     */
    public Goal setUserId(UUID userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>goal.current_weight</code>.
     */
    public Integer getCurrentWeight() {
        return this.currentWeight;
    }

    /**
     * Setter for <code>goal.current_weight</code>.
     */
    public Goal setCurrentWeight(Integer currentWeight) {
        this.currentWeight = currentWeight;
        return this;
    }

    /**
     * Getter for <code>goal.goal_weight</code>.
     */
    public Integer getGoalWeight() {
        return this.goalWeight;
    }

    /**
     * Setter for <code>goal.goal_weight</code>.
     */
    public Goal setGoalWeight(Integer goalWeight) {
        this.goalWeight = goalWeight;
        return this;
    }

    /**
     * Getter for <code>goal.progress_status</code>.
     */
    public String getProgressStatus() {
        return this.progressStatus;
    }

    /**
     * Setter for <code>goal.progress_status</code>.
     */
    public Goal setProgressStatus(String progressStatus) {
        this.progressStatus = progressStatus;
        return this;
    }

    /**
     * Getter for <code>goal.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>goal.created_on</code>.
     */
    public Goal setCreatedOn(LocalDateTime createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    /**
     * Getter for <code>goal.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>goal.updated_on</code>.
     */
    public Goal setUpdatedOn(LocalDateTime updatedOn) {
        this.updatedOn = updatedOn;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Goal other = (Goal) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        if (currentWeight == null) {
            if (other.currentWeight != null)
                return false;
        }
        else if (!currentWeight.equals(other.currentWeight))
            return false;
        if (goalWeight == null) {
            if (other.goalWeight != null)
                return false;
        }
        else if (!goalWeight.equals(other.goalWeight))
            return false;
        if (progressStatus == null) {
            if (other.progressStatus != null)
                return false;
        }
        else if (!progressStatus.equals(other.progressStatus))
            return false;
        if (createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!createdOn.equals(other.createdOn))
            return false;
        if (updatedOn == null) {
            if (other.updatedOn != null)
                return false;
        }
        else if (!updatedOn.equals(other.updatedOn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.currentWeight == null) ? 0 : this.currentWeight.hashCode());
        result = prime * result + ((this.goalWeight == null) ? 0 : this.goalWeight.hashCode());
        result = prime * result + ((this.progressStatus == null) ? 0 : this.progressStatus.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        result = prime * result + ((this.updatedOn == null) ? 0 : this.updatedOn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Goal (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(currentWeight);
        sb.append(", ").append(goalWeight);
        sb.append(", ").append(progressStatus);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
