/*
 * This file is generated by jOOQ.
 */
package co.tide.com.fitnessapp.db.jooq.tables;


import co.tide.com.fitnessapp.db.jooq.DefaultSchema;
import co.tide.com.fitnessapp.db.jooq.Keys;
import co.tide.com.fitnessapp.db.jooq.tables.records.GoalRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.16"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Goal extends TableImpl<GoalRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>goal</code>
     */
    public static final Goal GOAL = new Goal();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GoalRecord> getRecordType() {
        return GoalRecord.class;
    }

    /**
     * The column <code>goal.id</code>.
     */
    public final TableField<GoalRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>goal.user_id</code>.
     */
    public final TableField<GoalRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>goal.current_weight</code>.
     */
    public final TableField<GoalRecord, Integer> CURRENT_WEIGHT = createField(DSL.name("current_weight"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>goal.goal_weight</code>.
     */
    public final TableField<GoalRecord, Integer> GOAL_WEIGHT = createField(DSL.name("goal_weight"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>goal.progress_status</code>.
     */
    public final TableField<GoalRecord, String> PROGRESS_STATUS = createField(DSL.name("progress_status"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>goal.created_on</code>.
     */
    public final TableField<GoalRecord, LocalDateTime> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>goal.updated_on</code>.
     */
    public final TableField<GoalRecord, LocalDateTime> UPDATED_ON = createField(DSL.name("updated_on"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    private Goal(Name alias, Table<GoalRecord> aliased) {
        this(alias, aliased, null);
    }

    private Goal(Name alias, Table<GoalRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>goal</code> table reference
     */
    public Goal(String alias) {
        this(DSL.name(alias), GOAL);
    }

    /**
     * Create an aliased <code>goal</code> table reference
     */
    public Goal(Name alias) {
        this(alias, GOAL);
    }

    /**
     * Create a <code>goal</code> table reference
     */
    public Goal() {
        this(DSL.name("goal"), null);
    }

    public <O extends Record> Goal(Table<O> child, ForeignKey<O, GoalRecord> key) {
        super(child, key, GOAL);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<GoalRecord> getPrimaryKey() {
        return Keys.GOAL_PKEY;
    }

    @Override
    public List<UniqueKey<GoalRecord>> getKeys() {
        return Arrays.<UniqueKey<GoalRecord>>asList(Keys.GOAL_PKEY);
    }

    @Override
    public List<ForeignKey<GoalRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<GoalRecord, ?>>asList(Keys.GOAL__FK_GOAL_USER);
    }

    private transient User _user;

    public User user() {
        if (_user == null)
            _user = new User(this, Keys.GOAL__FK_GOAL_USER);

        return _user;
    }

    @Override
    public Goal as(String alias) {
        return new Goal(DSL.name(alias), this);
    }

    @Override
    public Goal as(Name alias) {
        return new Goal(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Goal rename(String name) {
        return new Goal(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Goal rename(Name name) {
        return new Goal(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, UUID, Integer, Integer, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
